<?php
// Array of 100 countries with ISO codes, names, and flag emojis
$countries = [
    ['cc' => 'US', 'name' => 'United States', 'flag' => '🇺🇸'],
    ['cc' => 'GB', 'name' => 'United Kingdom', 'flag' => '🇬🇧'],
    ['cc' => 'FR', 'name' => 'France', 'flag' => '🇫🇷'],
    ['cc' => 'DE', 'name' => 'Germany', 'flag' => '🇩🇪'],
    ['cc' => 'IT', 'name' => 'Italy', 'flag' => '🇮🇹'],
    ['cc' => 'ES', 'name' => 'Spain', 'flag' => '🇪🇸'],
    ['cc' => 'CA', 'name' => 'Canada', 'flag' => '🇨🇦'],
    ['cc' => 'AU', 'name' => 'Australia', 'flag' => '🇦🇺'],
    ['cc' => 'JP', 'name' => 'Japan', 'flag' => '🇯🇵'],
    ['cc' => 'KR', 'name' => 'South Korea', 'flag' => '🇰🇷'],
    ['cc' => 'CN', 'name' => 'China', 'flag' => '🇨🇳'],
    ['cc' => 'IN', 'name' => 'India', 'flag' => '🇮🇳'],
    ['cc' => 'BR', 'name' => 'Brazil', 'flag' => '🇧🇷'],
    ['cc' => 'MX', 'name' => 'Mexico', 'flag' => '🇲🇽'],
    ['cc' => 'RU', 'name' => 'Russia', 'flag' => '🇷🇺'],
    ['cc' => 'NL', 'name' => 'Netherlands', 'flag' => '🇳🇱'],
    ['cc' => 'BE', 'name' => 'Belgium', 'flag' => '🇧🇪'],
    ['cc' => 'CH', 'name' => 'Switzerland', 'flag' => '🇨🇭'],
    ['cc' => 'AT', 'name' => 'Austria', 'flag' => '🇦🇹'],
    ['cc' => 'SE', 'name' => 'Sweden', 'flag' => '🇸🇪'],
    ['cc' => 'NO', 'name' => 'Norway', 'flag' => '🇳🇴'],
    ['cc' => 'DK', 'name' => 'Denmark', 'flag' => '🇩🇰'],
    ['cc' => 'FI', 'name' => 'Finland', 'flag' => '🇫🇮'],
    ['cc' => 'IE', 'name' => 'Ireland', 'flag' => '🇮🇪'],
    ['cc' => 'PT', 'name' => 'Portugal', 'flag' => '🇵🇹'],
    ['cc' => 'GR', 'name' => 'Greece', 'flag' => '🇬🇷'],
    ['cc' => 'PL', 'name' => 'Poland', 'flag' => '🇵🇱'],
    ['cc' => 'CZ', 'name' => 'Czech Republic', 'flag' => '🇨🇿'],
    ['cc' => 'SK', 'name' => 'Slovakia', 'flag' => '🇸🇰'],
    ['cc' => 'HU', 'name' => 'Hungary', 'flag' => '🇭🇺'],
    ['cc' => 'RO', 'name' => 'Romania', 'flag' => '🇷🇴'],
    ['cc' => 'BG', 'name' => 'Bulgaria', 'flag' => '🇧🇬'],
    ['cc' => 'HR', 'name' => 'Croatia', 'flag' => '🇭🇷'],
    ['cc' => 'SI', 'name' => 'Slovenia', 'flag' => '🇸🇮'],
    ['cc' => 'LT', 'name' => 'Lithuania', 'flag' => '🇱🇹'],
    ['cc' => 'LV', 'name' => 'Latvia', 'flag' => '🇱🇻'],
    ['cc' => 'EE', 'name' => 'Estonia', 'flag' => '🇪🇪'],
    ['cc' => 'IS', 'name' => 'Iceland', 'flag' => '🇮🇸'],
    ['cc' => 'MT', 'name' => 'Malta', 'flag' => '🇲🇹'],
    ['cc' => 'CY', 'name' => 'Cyprus', 'flag' => '🇨🇾'],
    ['cc' => 'LU', 'name' => 'Luxembourg', 'flag' => '🇱🇺'],
    ['cc' => 'TR', 'name' => 'Turkey', 'flag' => '🇹🇷'],
    ['cc' => 'IL', 'name' => 'Israel', 'flag' => '🇮🇱'],
    ['cc' => 'SA', 'name' => 'Saudi Arabia', 'flag' => '🇸🇦'],
    ['cc' => 'AE', 'name' => 'UAE', 'flag' => '🇦🇪'],
    ['cc' => 'QA', 'name' => 'Qatar', 'flag' => '🇶🇦'],
    ['cc' => 'KW', 'name' => 'Kuwait', 'flag' => '🇰🇼'],
    ['cc' => 'BH', 'name' => 'Bahrain', 'flag' => '🇧🇭'],
    ['cc' => 'OM', 'name' => 'Oman', 'flag' => '🇴🇲'],
    ['cc' => 'JO', 'name' => 'Jordan', 'flag' => '🇯🇴'],
    ['cc' => 'LB', 'name' => 'Lebanon', 'flag' => '🇱🇧'],
    ['cc' => 'EG', 'name' => 'Egypt', 'flag' => '🇪🇬'],
    ['cc' => 'MA', 'name' => 'Morocco', 'flag' => '🇲🇦'],
    ['cc' => 'DZ', 'name' => 'Algeria', 'flag' => '🇩🇿'],
    ['cc' => 'TN', 'name' => 'Tunisia', 'flag' => '🇹🇳'],
    ['cc' => 'ZA', 'name' => 'South Africa', 'flag' => '🇿🇦'],
    ['cc' => 'NG', 'name' => 'Nigeria', 'flag' => '🇳🇬'],
    ['cc' => 'KE', 'name' => 'Kenya', 'flag' => '🇰🇪'],
    ['cc' => 'GH', 'name' => 'Ghana', 'flag' => '🇬🇭'],
    ['cc' => 'UG', 'name' => 'Uganda', 'flag' => '🇺🇬'],
    ['cc' => 'TZ', 'name' => 'Tanzania', 'flag' => '🇹🇿'],
    ['cc' => 'ET', 'name' => 'Ethiopia', 'flag' => '🇪🇹'],
    ['cc' => 'MU', 'name' => 'Mauritius', 'flag' => '🇲🇺'],
    ['cc' => 'AR', 'name' => 'Argentina', 'flag' => '🇦🇷'],
    ['cc' => 'CL', 'name' => 'Chile', 'flag' => '🇨🇱'],
    ['cc' => 'CO', 'name' => 'Colombia', 'flag' => '🇨🇴'],
    ['cc' => 'PE', 'name' => 'Peru', 'flag' => '🇵🇪'],
    ['cc' => 'VE', 'name' => 'Venezuela', 'flag' => '🇻🇪'],
    ['cc' => 'UY', 'name' => 'Uruguay', 'flag' => '🇺🇾'],
    ['cc' => 'PY', 'name' => 'Paraguay', 'flag' => '🇵🇾'],
    ['cc' => 'BO', 'name' => 'Bolivia', 'flag' => '🇧🇴'],
    ['cc' => 'EC', 'name' => 'Ecuador', 'flag' => '🇪🇨'],
    ['cc' => 'GT', 'name' => 'Guatemala', 'flag' => '🇬🇹'],
    ['cc' => 'CR', 'name' => 'Costa Rica', 'flag' => '🇨🇷'],
    ['cc' => 'PA', 'name' => 'Panama', 'flag' => '🇵🇦'],
    ['cc' => 'DO', 'name' => 'Dominican Republic', 'flag' => '🇩🇴'],
    ['cc' => 'JM', 'name' => 'Jamaica', 'flag' => '🇯🇲'],
    ['cc' => 'TH', 'name' => 'Thailand', 'flag' => '🇹🇭'],
    ['cc' => 'VN', 'name' => 'Vietnam', 'flag' => '🇻🇳'],
    ['cc' => 'MY', 'name' => 'Malaysia', 'flag' => '🇲🇾'],
    ['cc' => 'SG', 'name' => 'Singapore', 'flag' => '🇸🇬'],
    ['cc' => 'PH', 'name' => 'Philippines', 'flag' => '🇵🇭'],
    ['cc' => 'ID', 'name' => 'Indonesia', 'flag' => '🇮🇩'],
    ['cc' => 'BD', 'name' => 'Bangladesh', 'flag' => '🇧🇩'],
    ['cc' => 'PK', 'name' => 'Pakistan', 'flag' => '🇵🇰'],
    ['cc' => 'LK', 'name' => 'Sri Lanka', 'flag' => '🇱🇰'],
    ['cc' => 'NP', 'name' => 'Nepal', 'flag' => '🇳🇵'],
    ['cc' => 'AF', 'name' => 'Afghanistan', 'flag' => '🇦🇫'],
    ['cc' => 'IR', 'name' => 'Iran', 'flag' => '🇮🇷'],
    ['cc' => 'IQ', 'name' => 'Iraq', 'flag' => '🇮🇶'],
    ['cc' => 'KZ', 'name' => 'Kazakhstan', 'flag' => '🇰🇿'],
    ['cc' => 'UZ', 'name' => 'Uzbekistan', 'flag' => '🇺🇿'],
    ['cc' => 'KG', 'name' => 'Kyrgyzstan', 'flag' => '🇰🇬'],
    ['cc' => 'TJ', 'name' => 'Tajikistan', 'flag' => '🇹🇯'],
    ['cc' => 'TM', 'name' => 'Turkmenistan', 'flag' => '🇹🇲'],
    ['cc' => 'MN', 'name' => 'Mongolia', 'flag' => '🇲🇳'],
    ['cc' => 'NZ', 'name' => 'New Zealand', 'flag' => '🇳🇿'],
    ['cc' => 'FJ', 'name' => 'Fiji', 'flag' => '🇫🇯'],
    ['cc' => 'PG', 'name' => 'Papua New Guinea', 'flag' => '🇵🇬'],
    ['cc' => 'NC', 'name' => 'New Caledonia', 'flag' => '🇳🇨'],
    ['cc' => 'UA', 'name' => 'Ukraine', 'flag' => '🇺🇦'],
    ['cc' => 'BY', 'name' => 'Belarus', 'flag' => '🇧🇾'],
    ['cc' => 'MD', 'name' => 'Moldova', 'flag' => '🇲🇩'],
    ['cc' => 'RS', 'name' => 'Serbia', 'flag' => '🇷🇸'],
    ['cc' => 'ME', 'name' => 'Montenegro', 'flag' => '🇲🇪'],
    ['cc' => 'BA', 'name' => 'Bosnia and Herzegovina', 'flag' => '🇧🇦'],
    ['cc' => 'MK', 'name' => 'North Macedonia', 'flag' => '🇲🇰'],
    ['cc' => 'AL', 'name' => 'Albania', 'flag' => '🇦🇱'],
];
?>
